version: 2

project_name: service-bus-tui

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: service-bus-tui
    binary: service-bus-tui
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: service-bus-tui
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: service-bus-tui
    repository:
      owner: MonsieurTib
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/MonsieurTib/service-bus-tui"
    description: "A terminal-based explorer for Azure Service Bus"
    license: "MIT"
    install: |
      bin.install "service-bus-tui"
    test: |
      system "#{bin}/service-bus-tui", "--version"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

# winget:
#   - name: service-bus-tui
#     publisher: MonsieurTib
#     short_description: "A terminal-based explorer for Azure Service Bus"
#     license: "MIT"
#     homepage: "https://github.com/MonsieurTib/service-bus-tui"
#     publisher_url: "https://github.com/MonsieurTib"
#     publisher_support_url: "https://github.com/MonsieurTib/service-bus-tui/issues/new"
#     package_identifier: MonsieurTib.service-bus-tui
#     copyright: "MonsieurTib"
#     license_url: "https://github.com/MonsieurTib/service-bus-tui/blob/main/LICENSE"
#     tags:
#       - azure
#       - service-bus
#       - tui
#       - terminal
#       - cli
#     release_notes: "{{.Changelog}}"
#     commit_msg_template: "New version: MonsieurTib.service-bus-tui version {{ .Version }}"
#     repository:
#       owner: MonsieurTib
#       name: winget-pkgs
#       branch: "{{.ProjectName}}-{{.Version}}"
#       token: "{{ .Env.WINGET_PKGS_GITHUB_TOKEN }}"
#       pull_request:
#         enabled: true
#         base:
#           owner: microsoft
#           name: winget-pkgs
#           branch: master

chocolateys:
  - name: service-bus-tui
    owners: MonsieurTib
    authors: MonsieurTib
    title: service-bus-tui
    project_url: "https://github.com/MonsieurTib/service-bus-tui"
    copyright: "2026 MonsieurTib"
    license_url: "https://github.com/MonsieurTib/service-bus-tui/blob/main/LICENSE"
    require_license_acceptance: false
    project_source_url: "https://github.com/MonsieurTib/service-bus-tui"
    docs_url: "https://github.com/MonsieurTib/service-bus-tui/blob/main/README.md"
    bug_tracker_url: "https://github.com/MonsieurTib/service-bus-tui/issues"
    tags: "azure service-bus tui terminal cli"
    summary: "A terminal-based explorer for Azure Service Bus"
    description: |
      service-bus-tui is a terminal-based (TUI) explorer for Azure Service Bus.
      Browse namespaces, topics, queues, subscriptions, and peek messages
      directly from your terminal with vim-style keyboard navigation.
    release_notes: "https://github.com/MonsieurTib/service-bus-tui/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"

release:
  github:
    owner: MonsieurTib
    name: service-bus-tui
  draft: false
  prerelease: auto
