version: 2

project_name: service-bus-tui

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: service-bus-tui
    binary: service-bus-tui
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: service-bus-tui
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: service-bus-tui
    repository:
      owner: MonsieurTib
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/MonsieurTib/service-bus-tui"
    description: "A terminal-based explorer for Azure Service Bus"
    license: "MIT"
    install: |
      bin.install "service-bus-tui"
    test: |
      system "#{bin}/service-bus-tui", "--version"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

release:
  github:
    owner: MonsieurTib
    name: service-bus-tui
  draft: false
  prerelease: auto
